spring.application.name=springboot-web
server.port=8082
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
config.code=23232
config.username=jonas
config.message=Hola que tal
config.listOfValues=Hola,que,tal